services:
  postgres:
    image: postgres:13
    container_name: cinemora-api-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinemora-network

  redis:
    image: redis:6
    container_name: cinemora-api-redis
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - cinemora-network

  db_backup:
    profiles: [backup]
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: cinemora-api-backup
    restart: always
    environment:
    - PG_HOST=${POSTGRES_HOST}
    - PG_PORT=${POSTGRES_PORT}
    - PG_USER=${POSTGRES_USER}
    - PG_PASSWORD=${POSTGRES_PASSWORD}
    - PG_DATABASE=${POSTGRES_DB}
    - BACKUP_PATH=${BACKUP_PATH}
    - RETENTION_DAYS=${RETENTION_DAYS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - postgres_backups:/backup
    networks:
      - cinemora-network


networks:
  cinemora-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  postgres_backups:

