services:
  postgres:
    image: postgres:13
    container_name: cinemora-api-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5500:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinemora-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: cinemora-api-redis
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - cinemora-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cinemora-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - cinemora-network

  db_backup:
    profiles: [backup]
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: cinemora-api-backup
    restart: always
    environment:
      - PG_HOST=${POSTGRES_HOST}
      - PG_PORT=${POSTGRES_PORT}
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATABASE=${POSTGRES_DB}
      - BACKUP_PATH=${BACKUP_PATH}
      - RETENTION_DAYS=${RETENTION_DAYS}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - postgres_backups:/backup
    networks:
      - cinemora-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:${PORT}'
    volumes:
      - .:/app
    networks:
      - cinemora-network
    command: sh -c "npm run migration:run && npm run start:dev"

networks:
  cinemora-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  postgres_backups:
