#!/bin/sh

PG_HOST=${POSTGRES_HOST}
PG_PORT=${POSTGRES_PORT}
PG_USER=${POSTGRES_USER}
PG_PASSWORD=${POSTGRES_PASSWORD}
PG_DATABASE=${POSTGRES_DB}
BACKUP_PATH=${BACKUP_PATH}
RETENTION_DAYS=${RETENTION_DAYS}

mkdir -p "$BACKUP_PATH"

TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
FILENAME="${PG_DATABASE}_${TIMESTAMP}.sql"
ZIPFILE="${PG_DATABASE}_${TIMESTAMP}.zip"

export PGPASSWORD="$PG_PASSWORD"

pg_dump -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" "$PG_DATABASE" > "$BACKUP_PATH/$FILENAME"
zip -j "$BACKUP_PATH/$ZIPFILE" "$BACKUP_PATH/$FILENAME"
rm "$BACKUP_PATH/$FILENAME"

find "$BACKUP_PATH" -name "*.zip" -type f -mtime +$RETENTION_DAYS -exec rm {} \;
